### ISSUE TITLE
not an issue but a suggestion

### ISSUE THREAD

**Issue by uwezi** [cbm80amiga/DigiFont#1]
In order to make your library more portable than to just the Arduino world I suggest you make 2 small changes:

a) replace #include <Arduino.h> with #include <stdint.h> that appears to be the only part you need for your single instance of uint8_t

b) replace your binary constants in the form B10101010 with the standard-C syntax 0b10101010

I compiled your library with these changes together with my own driver for the SSD1306 in AtmelStudio 7 - no Arduino around...
https://www.sciencetronics.com/greenphotons/?p=2211

**Comment by cbm80amiga** [comment]
Done. I had to get rid of isdigit() function too because it was defined in Arduino.h at least in Arduino1.6.5

**Comment by uwezi** [comment]
Great!

Yes, I forgot that I also had to write my own isdigit() ...

**Comment by cbm80amiga** [comment]
It can be closed
