### ISSUE TITLE
Is there is any way to print digit from left to right??

### ISSUE THREAD

**Issue by Arman1515** [cbm80amiga/DigiFont#2]
Hi,I have a problem in printing digit.I want to print float value from left to right but I cant do it because it creates blob when decimal point shift from right to left.Is there is any way to get around it??
display: ST7789

**Comment by cbm80amiga** [comment]
Use dtostrf(value,4,1,buf) to convert float value to char buffer with fixed number of digits (total and after decimal point). In case of integer values you can use sprintf(buf,"%08d",value). It should solve such issues.
